version: '3.5'

services:

  hub:
    image: selenium/hub:3.10.0
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:3.10.0
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub

  firefox:
    image: selenium/node-firefox:3.10.0
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
